spring.application.name=sipafin

server.port=9050

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-summer-wave-b5iel4cu-pooler.c-7.us-east-2.aws.neon.tech/sipafin?user=neondb_owner&password=npg_DQhx8LpteO5I&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DQhx8LpteO5I
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# springdoc OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

spring.threads.virtual.enabled=true
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
# Increase server connection/timeouts if needed
server.tomcat.threads.max=200
server.tomcat.accept-count=200

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Pagination defaults
spring.data.web.pageable.default-page-size=1000
spring.data.web.pageable.max-page-size=100000
