package com.basiltech.sipafin.model;

public enum PettyCashTransactionType {
    OPENING_BALANCE,
    LOAN_RECEIVED,
    LOAN_REPAYMENT,
    COMMISSION_RECEIVED,
    EXPENSE,
    CASH_DISBURSEMENT,
    BANK_DEPOSIT,
    BANK_WITHDRAWAL,
    BRANCH_TRANSFER_IN,
    BRANCH_TRANSFER_OUT,
    ADJUSTMENT,
    REVERSAL
}